name: Artefakt-Build  # Schritt 2: Workflow Name

on:                    # Schritt 3: Trigger
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"       # SemVer-Tags wie v1.0.0
 defaults:
      run:
        working-directory: frontend 


jobs:                   # Schritt 4: Jobs definieren
  build:
    runs-on: ubuntu-latest

    steps:              # Schritt 5: Schritte im Job
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-${{ github.ref_name }}-${{ github.sha }}
          path: dist/
          retention-days: 14
